version: 2
jobs:
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:13.5.0-browsers
        steps:
            - checkout
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - run:
                name: Show current directory
                command: pwd
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
            - run:
                name: Install dependencies
                command: npm install
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: Linting
                command: npm run lint
            - run:
                name: Building
                command: npm run build-prod
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - dist
                    - package.json
                    - firebase.json
                    - .firebaserc
    test:
      docker:
        - image: circleci/node:13.5.0-browsers
      working_directory: ~/project
      steps:
        - checkout
        - run:
            name: Show current branch
            command: echo ${CIRCLE_BRANCH}
        - run:
            name: Show current directory
            command: pwd
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
        - run:
            name: Install dependencies
            command: npm install
        - save_cache:
            key: v1-dependencies-{{ checksum "package.json" }}
            paths:
              - node_modules
        - run:
            name: Testing
            command: npm run test-prod
    deploy:
        docker:
            - image: circleci/node:13.5.0-browsers
        working_directory: ~/project
        steps:
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - restore_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: Install Firebase
                command: npm install --save-dev firebase-tools
            - run:
                name: Deploy Master to Firebase
                command: npm run firebase-deploy

workflows:
    version: 2
    -deploy:
        jobs:
        - build
        - test:
            requires:
              - build
        - deploy:
            requires:
                - test
            filters:
                branches:
                    only: master
